services:
  futuopend:
    image: shing1211/futuopend:latest
    container_name: futuopend
    stdin_open: true
    tty: true
    volumes:
      - volume:/root/.com.futunn.FutuOpenD
    secrets:
      - source: rsa-key
        target: ${RSA_FILE_PATH}
      - source: config
        target: ${FUTU_OPEND_XML_PATH}
    ports:
      - 11111:11111
    env_file:
      - path: ./.env
        required: true # default
volumes:
  volume:

secrets:
  rsa-key:
    file: ${RSA_FILE_LOCAL_PATH}
  config:
    file: ${FUTU_OPEND_XML_LOCAL_PATH}
