# syntax=docker/dockerfile:1
#
# Copyright 2026 shing1211
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Rocky Linux 9 multi-stage build.
# Each (arch) variant is a separate build target.
#
# Usage:
#   docker build --target final .
#   docker buildx build --platform linux/amd64,linux/arm64 --target final .
#

ARG FUTU_OPEND_VER=10.5.6508

FROM rockylinux:9 AS base-amd64
FROM rockylinux:9 AS base-arm64

FROM base-${TARGETARCH:-amd64} AS build
ARG FUTU_OPEND_VER

WORKDIR /tmp
RUN curl -fsSL "https://softwaredownload.futunn.com/Futu_OpenD_${FUTU_OPEND_VER}_Centos7.tar.gz" \
         -o Futu_OpenD.tar.gz \
    && tar -xzf Futu_OpenD.tar.gz \
    && rm Futu_OpenD.tar.gz

FROM base-${TARGETARCH:-amd64} AS final
